### ISSUE TITLE
Bug : panic: runtime error: index out of range

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/hal#3]
## issue

```
git clone https://github.com/snowdrop/component-operator-demo.git && cd component-operator-demo
mvn clean package
cd fruit-backend-sb
kreate init
kreate push
INFO[0001] Component for fruit-backend-sb initialized. Wait a few seconds for it to be ready!
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/snowdrop/kreate/pkg/kreate/cli/push.(*options).Run(0x2b45b70, 0x0, 0xc00015b500)
	/Users/dabou/Code/snowdrop/kreate/pkg/kreate/cli/push/push.go:45 +0x820
github.com/snowdrop/kreate/pkg/cmdutil.GenericRun(0x20a6980, 0x2b45b70, 0xc0002e6280, 0x2b45b70, 0x0, 0x0)
	/Users/dabou/Code/snowdrop/kreate/pkg/cmdutil/runnable.go:18 +0x245
github.com/snowdrop/kreate/pkg/kreate/cli/push.NewCmdPush.func1(0xc0002e6280, 0x2b45b70, 0x0, 0x0)
	/Users/dabou/Code/snowdrop/kreate/pkg/kreate/cli/push/push.go:96 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0002e6280, 0x2b45b70, 0x0, 0x0, 0xc0002e6280, 0x2b45b70)
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000215b80, 0x1c8b19c, 0xc000199f88, 0x10077cf)
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/Users/dabou/Code/snowdrop/kreate/cmd/kreate.go:11 +0x2c
```

**Comment by metacosm** [comment]
@cmoulliard I assume that this error has been addressed, right?

**Comment by metacosm** [comment]
Obsolete.
