### ISSUE TITLE
hal doesn't wait for build to finish properly

### ISSUE THREAD

**Issue by Ladicek** [halkyonio/hal#61]
When I issue `hal component push`, I get `Performing build`, the pod log clearly shows that Maven started running, and very quickly I get `Restarting app` and the pod log starts showing attempts to start `/deployments/app.jar`. The Maven build didn't finish yet, though. The pod log now has mixed outputs of Maven and the attempts to start the app.

This most likely isn't an issue in hal itself -- hal simply waits for `/var/lib/supervisord/bin/supervisord ctl start build` to finish -- but I'm not sure where else to file this. It's a deficiency of the `supervisord`-based architecture.

It's quite simple to workaround this in `hal` itself; add this after the code that remotely executes `/var/lib/supervisord/bin/supervisord ctl start build`:

```go
if err = c.ExecCommand(podName, []string{"bash", "-c", "while /var/lib/supervisord/bin/supervisord ctl status build | grep RUNNING; do sleep 1; done"},
	"Waiting for build to finish"); err != nil {
	return err
}
```

**Comment by Ladicek** [comment]
In combination with https://github.com/halkyonio/operator/issues/177, this can also cause really weird-looking errors when the application was already successfully pushed and is being pushed again. They tend to heal, because of that endless restart, but the pod log can have weird error messages (probably due to things like half-copied uberjars etc.).

**Comment by metacosm** [comment]
All these issues should be addressed at the operator level, in my opinion. Or rather the combination of the supervisor and the operator. The problem with using only an operator means that you cannot react to what happens at the app level because the operator only knows about k8s-level events. So I'd argue that the solution to these problems is a better supervisor infra since that's where the problem should be addressed, not in duplicated logic/work-arounds in clients.

**Comment by cmoulliard** [comment]
I also observe the same problem when we do a new `hal component push -c quarkus-rest-1`

```
hal component push -c quarkus-rest-1                                  
Local changes detected for 'quarkus-rest-1' component: about to push source code to remote cluster
 ✓  Uploading /Users/dabou/Temp/quarkus/demo/quarkus-rest-1.tar
 ✓  Cleaning up component
 ✓  Extracting source on the remote cluster
 ✓  Performing build
 ✓  Restarting app
 ✓  Successfully pushed 'quarkus-rest-1' component to remote cluster
```

then we got this error from the pod's log as the supervisord re-start the application without to wait till build ends

```

[INFO] --- quarkus-maven-plugin:1.1.1.Final:build (default) @ quarkus-rest ---
--
  | [INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
  | [INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building fat jar: /usr/src/target/quarkus-rest-1.0-SNAPSHOT-runner.jar
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/LGPL-3.0.txt entry from com.github.fge:msg-simple::jar:1.1(compile) will be ignored. Existing file was provided by com.github.fge:btf::jar:1.2(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/ASL-2.0.txt entry from com.github.fge:msg-simple::jar:1.1(compile) will be ignored. Existing file was provided by com.github.fge:btf::jar:1.2(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/LGPL-3.0.txt entry from com.github.fge:jackson-coreutils::jar:1.6(compile) will be ignored. Existing file was provided by com.github.fge:btf::jar:1.2(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/ASL-2.0.txt entry from com.github.fge:jackson-coreutils::jar:1.6(compile) will be ignored. Existing file was provided by com.github.fge:btf::jar:1.2(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/LGPL-3.0.txt entry from com.github.fge:json-patch::jar:1.9(compile) will be ignored. Existing file was provided by com.github.fge:btf::jar:1.2(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/ASL-2.0.txt entry from com.github.fge:json-patch::jar:1.9(compile) will be ignored. Existing file was provided by com.github.fge:btf::jar:1.2(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/license.txt entry from org.springframework:spring-expression::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/notice.txt entry from org.springframework:spring-expression::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/license.txt entry from org.springframework:spring-context::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/notice.txt entry from org.springframework:spring-context::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/spring.handlers entry from org.springframework:spring-context::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/spring.schemas entry from org.springframework:spring-context::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/spring.tooling entry from org.springframework:spring-context::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/license.txt entry from org.springframework:spring-beans::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/notice.txt entry from org.springframework:spring-beans::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/spring.handlers entry from org.springframework:spring-beans::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/spring.schemas entry from org.springframework:spring-beans::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/spring.tooling entry from org.springframework:spring-beans::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/license.txt entry from org.springframework:spring-core::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/notice.txt entry from org.springframework:spring-core::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/license.txt entry from org.springframework:spring-web::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Duplicate entry META-INF/notice.txt entry from org.springframework:spring-web::jar:5.1.8.RELEASE(compile) will be ignored. Existing file was provided by org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [com.github.fge:jackson-coreutils::jar:1.6(compile), com.github.fge:btf::jar:1.2(compile), com.github.fge:msg-simple::jar:1.1(compile), com.github.fge:json-patch::jar:1.9(compile)] contain duplicate files, e.g. META-INF/ASL-2.0.txt
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.springframework:spring-context::jar:5.1.8.RELEASE(compile), org.springframework:spring-beans::jar:5.1.8.RELEASE(compile), org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)] contain duplicate files, e.g. META-INF/spring.schemas
  | [WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.springframework:spring-expression::jar:5.1.8.RELEASE(compile), org.springframework:spring-web::jar:5.1.8.RELEASE(compile), org.springframework:spring-context::jar:5.1.8.RELEASE(compile), org.springframework:spring-beans::jar:5.1.8.RELEASE(compile), org.springframework:spring-core::jar:5.1.8.RELEASE(compile), org.springframework:spring-aop::jar:5.1.8.RELEASE(compile)] contain duplicate files, e.g. META-INF/license.txt
  | [INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 17210ms
  | [INFO] ------------------------------------------------------------------------
  | [INFO] BUILD SUCCESS
  | [INFO] ------------------------------------------------------------------------
  | [INFO] Total time:  32.920 s
  | [INFO] Finished at: 2020-01-21T10:20:39Z
  | [INFO] ------------------------------------------------------------------------
  | time="2020-01-21T10:20:39Z" level=info msg="program stopped with status:exit status 0" program=build
  | time="2020-01-21T10:20:39Z" level=info msg="Don't start the stopped program because its autorestart flag is false" program=build
  | Exception in thread "vert.x-acceptor-thread-0" java.lang.NoClassDefFoundError: org/slf4j/helpers/MessageFormatter
  | at org.jboss.slf4j.JBossLoggerAdapter.log(JBossLoggerAdapter.java:57)
  | at io.netty.util.internal.logging.LocationAwareSlf4JLogger.log(LocationAwareSlf4JLogger.java:46)
  | at io.netty.util.internal.logging.LocationAwareSlf4JLogger.error(LocationAwareSlf4JLogger.java:249)
  | at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:843)
  | at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
  | at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
  | at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
  | at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1089)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  | time="2020-01-21T11:33:35Z" level=debug msg="no auth required"


 ...  
```

The Workaround (which is not a real workaround) is to do manually a `supervisord ctl stop/start run`

**Comment by cmoulliard** [comment]
The problem that we have here is that ideally the existing java application launched by the command `/var/lib/supervisord/bin/supervisord ctl start run` should be stopped 
using the command ` /var/lib/supervisord/bin/supervisord ctl stop run` 

before to start a new maven build `/var/lib/supervisord/bin/supervisord ctl start build` 
and finally to-restart the java application `/var/lib/supervisord/bin/supervisord ctl start run`

**Comment by Ladicek** [comment]
That's just a half of it. `supervisord ctl start|stop xxx` doesn't wait until the action is done, which is the ultimate source of weird behavior. (For example, if you `start build`, then that's a short-running process and you don't want to `start run` until the build finishes.)

**Comment by cmoulliard** [comment]
I did a test using workaround of @Ladicek and that works or quarkus

Scenario:
- Create a new component
- Next push it
```
 hal component push -c quarkus-rest-1
Local changes detected for 'quarkus-rest-1' component: about to push source code to remote cluster
 ✓  Uploading /Users/dabou/Temp/quarkus/demo/quarkus-rest-1.tar
 ✓  Cleaning up component
 ✓  Extracting source on the remote cluster
 ✓  Performing build
 ✓  Waiting for build to finish
 ✓  Restarting app
 ✓  Successfully pushed 'quarkus-rest-1' component to remote cluster
```
- Change the code locally
- Push again the project
hal component push -c quarkus-rest-1
Local changes detected for 'quarkus-rest-1' component: about to push source code to remote cluster
 ✓  Uploading /Users/dabou/Temp/quarkus/demo/quarkus-rest-1.tar
 ✓  Cleaning up component
 ✓  Extracting source on the remote cluster
 ✓  Performing build
 ✓  Waiting for build to finish
 ✓  Restarting app
 ✓  Successfully pushed 'quarkus-rest-1' component to remote cluster
```

So I will push the commit with Ladislav's trick

**Comment by cmoulliard** [comment]
Can you make a new Thornthail test @Ladicek please ?

**Comment by Ladicek** [comment]
I don't have the cycles for that now, sorry.

**Comment by iocanel** [comment]
@cmoulliard: I kinda lost track of this issue. Is thre still work to be done here?

**Comment by cmoulliard** [comment]
> Is thre still work to be done here?

No but we wait that @Ladicek do some tests to confirm that we can close it

**Comment by Ladicek** [comment]
If you have just applied the workaround I suggested in this issue, then feel free to close this. Otherwise, I can't tell when I'll be able to get to this.
